services:
    minsal_maestros.admin.ctl_pais:
        class: Minsal\MaestrosBundle\Admin\CtlPaisAdmin
        arguments: [~, Minsal\MaestrosBundle\Entity\CtlPais, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CtlPais}
